#!/usr/bin/env Rscript

# title: diagnostic_chr1_followup.R
# project: BIOL624 Final Project -- Selection Detection in Lady Beetles
# author: Reina Hastings
# contact: reinahastings13@gmail.com
# date created: 2026-05-01
# last modified: 2026-05-01
#
# purpose:
#   Manhattan-scatter diagnostic, chr-1 follow-up between Task 3 and Task 4.
#   Task 3 found that chr 1 (NC_058189.1) dominates per-chromosome outlier
#   density in every one of the 6 pairwise comparisons, including the
#   among-invasive ones where there has been minimal time for parallel
#   locus-specific selection. That cross-comparison universality is the
#   signal that warrants checking before any SNP-resolution clustering
#   analysis (Task 4) is meaningful. This script runs four checks to
#   distinguish "real chromosomal selection target" from "chr-1 specific
#   technical artifact" hypotheses:
#
#     Check 1. SNP density by chromosome, comparing PLINK QC universe
#              (pre-FST-filter) against the FST-callable universe
#              (post-NA-drop) and against length. Chr 1 outlying high in
#              SNPs/Mb at either level would point at variant-calling
#              hotspots (paralog mismapping, repeat-region calls, etc.).
#     Check 2. Spatial distribution of chr-1 outliers in 1 Mb bins.
#              Distinguishes "chromosome-wide elevation" (consistent with
#              broad biological cause) from "narrow peak" (specific
#              selection target) from "centromere/telomere clustering"
#              (mappability artifact).
#     Check 3. F_ST magnitude of chr-1 outliers vs. other-chromosome
#              outliers. If chr-1 outliers sit at systematically lower
#              F_ST than other-chrom outliers, chr 1 is over-represented
#              just because it has lots of borderline-FST SNPs (artifact
#              of the genome-wide percentile threshold). If chr-1
#              outliers match or exceed other-chrom outliers in F_ST,
#              the chr-1 signal is driven by genuinely high-FST SNPs.
#     Check 4. MAF distribution of chr-1 SNPs vs. other chromosomes
#              (genome-wide PLINK universe, not just outliers). Chr-1
#              MAF inflated relative to other chromosomes is a hallmark
#              of paralog-mismapping or repeat-region SNP-calling
#              artifacts (false heterozygotes inflate MAF toward 0.5).
#
# inputs:
#   - results/fst/{COMP}/fst_genomewide/{CHROM}.filtered.weir.fst
#       Per-SNP F_ST. NA-drop = post-filter for check 1; values for check 3.
#   - results/per_snp_selection_scan/outliers_1pct_chifiltered.tsv
#       Outlier set used for checks 2 and 3.
#   - data/plink/ladybug_snps.bim
#       PLINK QC universe (pre-FST-filter SNP count for check 1).
#   - <generated by this script via plink --freq>
#       /tmp/ladybug_maf.frq
#       Genome-wide MAF for check 4. The script regenerates it if absent.
#   - VCF header contigs (for chromosome lengths). Read once via zcat.
#
# outputs:
#   - figures/diagnostic/chr1_followup/
#       check1_snp_density_by_chrom.png
#       check2_chr1_spatial_distribution.png
#       check3_fst_chr1_vs_other.png
#       check4_maf_chr1_vs_other.png
#       summary_panel.png         (4-panel combined view)
#   - results/diagnostic/chr1_followup_summary.tsv
#       One row per chromosome with: length_mb, plink_snps, plink_snps_per_mb,
#       fst_snps_<comp>, fst_snps_per_mb_<comp>, mean_maf, median_maf.
#   - results/diagnostic/chr1_followup_check3.tsv
#       Per-comparison F_ST stats split by chr-1 vs other-chrom outliers.
#   - results/diagnostic/chr1_followup_run.log
#
# usage example:
#   Rscript scripts/diagnostic_chr1_followup.R

suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(patchwork)
})

# --- Paths ------------------------------------------------------------------

project_root <- if (file.exists("results/fst")) {
  "."
} else if (file.exists("../results/fst")) {
  ".."
} else {
  stop("Cannot locate results/fst/. Run from project root or scripts/.")
}

fst_base    <- file.path(project_root, "results/fst")
outliers_in <- file.path(project_root,
                         "results/per_snp_selection_scan/outliers_1pct_chifiltered.tsv")
plink_bim   <- file.path(project_root, "data/plink/ladybug_snps.bim")
vcf_header  <- file.path(project_root,
                         "data/VARIANTS_BY_CHR/FILTERED_CHR_VCFS/NC_058189.1.filtered.vcf.gz")

maf_path    <- "/tmp/ladybug_maf.frq"
plink_bin   <- "/Users/reina/miniconda3/envs/pop_gen/bin/plink"

fig_dir <- file.path(project_root, "figures/diagnostic/chr1_followup")
out_dir <- file.path(project_root, "results/diagnostic")
out_summary <- file.path(out_dir, "chr1_followup_summary.tsv")
out_check3  <- file.path(out_dir, "chr1_followup_check3.tsv")
out_log     <- file.path(out_dir, "chr1_followup_run.log")

dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# --- Configuration ----------------------------------------------------------

chi_comparisons      <- c("CHI_vs_EEU", "CHI_vs_USA", "CHI_vs_WEU")
invasive_comparisons <- c("EEU_vs_USA", "EEU_vs_WEU", "USA_vs_WEU")
all_comparisons      <- c(chi_comparisons, invasive_comparisons)
autosomes <- sprintf("NC_0581%02d.1", 89:97)
chr1      <- "NC_058189.1"
chrom_labels <- setNames(seq_along(autosomes), autosomes)

# --- Logging ----------------------------------------------------------------

log_lines <- character()
log_msg <- function(...) {
  line <- paste0(...)
  log_lines <<- c(log_lines, line)
  cat(line, "\n", sep = "")
}

log_msg("=== chr-1 follow-up diagnostic ===")

# --- Step 0: Chromosome lengths from VCF header ----------------------------

log_msg("\n[0] Parsing chromosome lengths from VCF header")

# A single per-chromosome VCF carries the full assembly contig list in
# its header, so one zcat is enough.
hdr <- system(sprintf("/usr/bin/zcat < %s 2>/dev/null | head -300", shQuote(vcf_header)),
              intern = TRUE)
contig_lines <- grep("^##contig=", hdr, value = TRUE)
parse_contig <- function(line) {
  m <- regmatches(line, regexec(
    "ID=([^,>]+),length=([0-9]+)", line))[[1]]
  if (length(m) != 3) return(NULL)
  tibble(chrom = m[2], length_bp = as.numeric(m[3]))
}
chrom_lengths <- bind_rows(lapply(contig_lines, parse_contig)) %>%
  filter(chrom %in% autosomes) %>%
  mutate(length_mb = length_bp / 1e6) %>%
  arrange(match(chrom, autosomes))
log_msg("  chromosome lengths (Mb):")
for (i in seq_len(nrow(chrom_lengths))) {
  log_msg(sprintf("    chr%d  %s  %6.2f Mb",
                  chrom_labels[chrom_lengths$chrom[i]],
                  chrom_lengths$chrom[i],
                  chrom_lengths$length_mb[i]))
}

# --- Step 1: Per-chromosome SNP densities (check 1) ------------------------

log_msg("\n[1] Check 1: SNP density by chromosome (pre-filter and post-filter)")

# Pre-filter universe: PLINK BIM (post-PLINK-QC; this is the "pre-FST-filter"
# count for the purposes of asking whether chr 1 is anomalously SNP-rich
# upstream of FST).
log_msg("  loading PLINK BIM...")
bim <- fread(plink_bim, sep = "\t", header = FALSE,
             col.names = c("chrom", "snp_id", "cm", "pos", "a1", "a2"),
             colClasses = c(chrom = "character"))
bim <- bim[chrom %in% autosomes]
plink_counts <- bim[, .(plink_snps = .N), by = chrom]
log_msg(sprintf("  PLINK BIM: %d SNPs across %d autosomes",
                nrow(bim), length(unique(bim$chrom))))

# Post-filter: per-comparison FST file with NA dropped (matches the per-SNP
# scan denominator).
read_fst_one <- function(comp, chrom) {
  f <- file.path(fst_base, comp, "fst_genomewide",
                 sprintf("%s.filtered.weir.fst", chrom))
  dt <- fread(f, sep = "\t", header = TRUE,
              colClasses = c(CHROM = "character",
                             POS = "integer",
                             WEIR_AND_COCKERHAM_FST = "double"))
  dt[!is.na(WEIR_AND_COCKERHAM_FST)]
}

fst_count_rows <- vector("list", length(all_comparisons) * length(autosomes))
fst_value_rows <- vector("list", length(all_comparisons) * length(autosomes))
k <- 1
for (comp in all_comparisons) {
  for (chrom in autosomes) {
    dt <- read_fst_one(comp, chrom)
    fst_count_rows[[k]] <- tibble(comparison = comp, chrom = chrom,
                                  fst_snps = nrow(dt))
    fst_value_rows[[k]] <- tibble(comparison = comp, chrom = chrom,
                                  pos = dt$POS,
                                  fst = dt$WEIR_AND_COCKERHAM_FST)
    k <- k + 1
  }
  log_msg(sprintf("  %-12s FST loaded", comp))
}
fst_counts <- bind_rows(fst_count_rows)
fst_values <- bind_rows(fst_value_rows)

# Build per-chromosome summary: PLINK count, mean FST count across 6 comps,
# densities (SNPs / Mb).
summary_df <- chrom_lengths %>%
  left_join(plink_counts, by = "chrom") %>%
  mutate(plink_snps_per_mb = plink_snps / length_mb)

# FST counts: average across 6 comparisons since they are very similar.
fst_count_wide <- fst_counts %>%
  pivot_wider(names_from = comparison, values_from = fst_snps,
              names_prefix = "fst_snps_")
summary_df <- summary_df %>%
  left_join(fst_count_wide, by = "chrom") %>%
  mutate(
    fst_snps_mean_across_comps = rowMeans(across(starts_with("fst_snps_"))),
    fst_snps_per_mb            = fst_snps_mean_across_comps / length_mb,
    chrom_idx                  = chrom_labels[chrom],
    is_chr1                    = chrom == chr1
  )

# Plot check 1.
make_density_plot <- function(df, ycol, ylab, title) {
  fill_col <- ifelse(df$is_chr1, "#D55E00", "#5B8AB7")
  ggplot(df, aes(x = factor(chrom_idx), y = .data[[ycol]])) +
    geom_col(fill = fill_col, color = "grey20", linewidth = 0.2) +
    geom_text(aes(label = sprintf("%.0f", .data[[ycol]])),
              vjust = -0.4, size = 2.5, color = "grey20") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
    labs(title = title,
         x = "Chromosome (1-9)", y = ylab) +
    theme_bw(base_size = 9) +
    theme(plot.title = element_text(face = "bold", size = 10),
          panel.grid.major.x = element_blank(),
          panel.grid.minor   = element_blank())
}

p1a <- make_density_plot(summary_df, "plink_snps_per_mb",
                         "PLINK SNPs / Mb",
                         "Pre-filter SNP density (PLINK QC universe)")
p1b <- make_density_plot(summary_df, "fst_snps_per_mb",
                         "FST-callable SNPs / Mb (mean of 6 comps)",
                         "Post-filter SNP density (FST non-NA universe)")
p1 <- (p1a | p1b) +
  plot_annotation(
    title = "Check 1: SNP density by chromosome",
    subtitle = "Orange = chr 1; blue = other autosomes. Bar labels = SNPs/Mb.",
    theme = theme(plot.title = element_text(face = "bold", size = 11),
                  plot.subtitle = element_text(size = 9))
  )
ggsave(file.path(fig_dir, "check1_snp_density_by_chrom.png"),
       p1, width = 200, height = 100, units = "mm", dpi = 200)
log_msg(sprintf("  wrote: check1_snp_density_by_chrom.png"))
log_msg("  per-chromosome density (PLINK and mean-FST):")
for (i in seq_len(nrow(summary_df))) {
  r <- summary_df[i, ]
  log_msg(sprintf("    chr%d  %6.2f Mb  PLINK %6.0f SNPs (%6.1f /Mb)   FST %6.0f SNPs (%6.1f /Mb)",
                  r$chrom_idx, r$length_mb, r$plink_snps, r$plink_snps_per_mb,
                  r$fst_snps_mean_across_comps, r$fst_snps_per_mb))
}

# --- Step 2: Spatial distribution of chr-1 outliers (check 2) -------------

log_msg("\n[2] Check 2: spatial distribution of chr-1 outliers in 1 Mb bins")

out_dt <- fread(outliers_in, sep = "\t", header = TRUE)
chr1_outliers <- out_dt[chrom == chr1]
log_msg(sprintf("  chr-1 outliers in upstream file: %d (across all 6 comps)",
                nrow(chr1_outliers)))

chr1_len_mb <- chrom_lengths$length_mb[chrom_lengths$chrom == chr1]
bin_edges <- seq(0, ceiling(chr1_len_mb), by = 1)
chr1_bins <- chr1_outliers %>%
  as_tibble() %>%
  mutate(bin_mb = floor(pos / 1e6)) %>%
  count(comparison, bin_mb, name = "n_outliers")

# Fill in zero-count bins for all comparisons.
grid_chr1 <- crossing(comparison = all_comparisons, bin_mb = 0:floor(chr1_len_mb))
chr1_bins <- grid_chr1 %>%
  left_join(chr1_bins, by = c("comparison", "bin_mb")) %>%
  mutate(n_outliers = replace_na(n_outliers, 0L),
         comp_type = if_else(comparison %in% chi_comparisons,
                             "CHI_vs_invasive", "Among_invasive"))

p2 <- ggplot(chr1_bins, aes(x = bin_mb, y = n_outliers,
                             fill = comp_type)) +
  geom_col(width = 1, color = NA) +
  scale_fill_manual(values = c(CHI_vs_invasive = "#E07B7B",
                               Among_invasive  = "#5B8AB7")) +
  facet_wrap(~ comparison, ncol = 3, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, ceiling(chr1_len_mb), 10)) +
  labs(
    title    = "Check 2: chr-1 outlier counts in 1 Mb bins",
    subtitle = sprintf("Chr 1 length: %.2f Mb. Each bar = one 1 Mb bin.",
                       chr1_len_mb),
    x = "Position along chr 1 (Mb)",
    y = "Outlier count in bin",
    fill = NULL
  ) +
  theme_bw(base_size = 9) +
  theme(plot.title = element_text(face = "bold", size = 10),
        legend.position = "bottom",
        strip.background = element_rect(fill = "grey95", color = NA),
        panel.grid.minor = element_blank())
ggsave(file.path(fig_dir, "check2_chr1_spatial_distribution.png"),
       p2, width = 230, height = 130, units = "mm", dpi = 200)
log_msg(sprintf("  wrote: check2_chr1_spatial_distribution.png"))

# Spatial dispersion summary: number of bins with >= 1 outlier vs total.
chr1_bin_summary <- chr1_bins %>%
  group_by(comparison) %>%
  summarise(
    n_bins_total       = n(),
    n_bins_with_any    = sum(n_outliers > 0),
    pct_bins_with_any  = 100 * mean(n_outliers > 0),
    max_bin_count      = max(n_outliers),
    max_bin_position_mb = bin_mb[which.max(n_outliers)],
    .groups = "drop"
  )
log_msg("  chr-1 spatial summary:")
for (i in seq_len(nrow(chr1_bin_summary))) {
  r <- chr1_bin_summary[i, ]
  log_msg(sprintf("    %-12s bins_with_any=%2d/%d (%.1f%%)  max bin=%d outliers @ %d Mb",
                  r$comparison, r$n_bins_with_any, r$n_bins_total,
                  r$pct_bins_with_any, r$max_bin_count, r$max_bin_position_mb))
}

# --- Step 3: F_ST magnitude of chr-1 outliers vs others (check 3) ---------

log_msg("\n[3] Check 3: FST magnitude of chr-1 outliers vs other-chrom outliers")

out_auto <- out_dt[chrom %in% autosomes] %>% as_tibble() %>%
  mutate(group = if_else(chrom == chr1, "chr_1", "other_autosomes"))

check3_summary <- out_auto %>%
  group_by(comparison, group) %>%
  summarise(n = n(),
            mean_fst   = mean(fst),
            median_fst = median(fst),
            sd_fst     = sd(fst),
            min_fst    = min(fst),
            q25_fst    = quantile(fst, 0.25),
            q75_fst    = quantile(fst, 0.75),
            max_fst    = max(fst),
            .groups = "drop")
write_tsv(check3_summary, out_check3, na = "NA")
log_msg(sprintf("  wrote: %s", out_check3))
log_msg("  per-comparison median FST among outliers (chr_1 vs others):")
for (comp in all_comparisons) {
  rows <- check3_summary %>% filter(comparison == comp)
  c1 <- rows %>% filter(group == "chr_1")
  ot <- rows %>% filter(group == "other_autosomes")
  log_msg(sprintf("    %-12s chr_1 median=%.3f (n=%d)   others median=%.3f (n=%d)   delta=%+.3f",
                  comp,
                  c1$median_fst, c1$n,
                  ot$median_fst, ot$n,
                  c1$median_fst - ot$median_fst))
}

p3 <- ggplot(out_auto, aes(x = comparison, y = fst, fill = group)) +
  geom_violin(scale = "width", trim = TRUE, color = "grey20",
              linewidth = 0.2, position = position_dodge(width = 0.85),
              width = 0.8) +
  geom_boxplot(width = 0.18, outlier.size = 0.4, color = "grey20",
               position = position_dodge(width = 0.85), linewidth = 0.2,
               fill = "white", alpha = 0.6) +
  scale_fill_manual(values = c(chr_1 = "#D55E00",
                                other_autosomes = "#5B8AB7"),
                    labels = c("chr 1", "other autosomes")) +
  labs(
    title    = "Check 3: F_ST distribution among outliers, chr 1 vs other autosomes",
    subtitle = "Violins show distribution shape; boxplots show median and IQR.",
    x = NULL, y = expression(F[ST]),
    fill = "Group"
  ) +
  theme_bw(base_size = 9) +
  theme(plot.title = element_text(face = "bold", size = 10),
        axis.text.x = element_text(angle = 25, hjust = 1),
        legend.position = "bottom")
ggsave(file.path(fig_dir, "check3_fst_chr1_vs_other.png"),
       p3, width = 200, height = 120, units = "mm", dpi = 200)
log_msg("  wrote: check3_fst_chr1_vs_other.png")

# --- Step 4: MAF distribution of chr-1 SNPs vs others (check 4) -----------

log_msg("\n[4] Check 4: MAF distribution of chr-1 SNPs vs other autosomes")

if (!file.exists(maf_path)) {
  log_msg("  computing genome-wide MAF with plink (this happens once)...")
  cmd <- sprintf("%s --bfile %s --freq --out %s --allow-extra-chr",
                 shQuote(plink_bin),
                 shQuote(file.path(project_root, "data/plink/ladybug_snps")),
                 shQuote(sub("\\.frq$", "", maf_path)))
  system(cmd, ignore.stdout = TRUE)
}

frq <- fread(maf_path, header = TRUE,
             col.names = c("CHR", "SNP", "A1", "A2", "MAF", "NCHROBS"),
             colClasses = list(character = c("CHR","SNP","A1","A2"),
                               numeric   = c("MAF","NCHROBS")))
# PLINK's MAF column has the minor-allele frequency.
frq_auto <- frq[CHR %in% autosomes]
frq_auto[, group := ifelse(CHR == chr1, "chr_1", "other_autosomes")]

maf_summary <- frq_auto[, .(
  n           = .N,
  mean_maf    = mean(MAF, na.rm = TRUE),
  median_maf  = median(MAF, na.rm = TRUE),
  sd_maf      = sd(MAF, na.rm = TRUE),
  pct_above_4 = 100 * mean(MAF >= 0.40, na.rm = TRUE),
  pct_below_05 = 100 * mean(MAF < 0.05, na.rm = TRUE)
), by = group]
log_msg("  MAF summary (PLINK QC universe):")
for (i in seq_len(nrow(maf_summary))) {
  r <- maf_summary[i, ]
  log_msg(sprintf("    %-15s n=%7d  mean=%.4f  median=%.4f  sd=%.4f  pct_>=0.40=%.2f%%  pct_<0.05=%.2f%%",
                  r$group, r$n, r$mean_maf, r$median_maf, r$sd_maf,
                  r$pct_above_4, r$pct_below_05))
}

# Add MAF summary as additional columns of summary_df.
maf_per_chrom <- frq_auto[, .(mean_maf = mean(MAF, na.rm = TRUE),
                              median_maf = median(MAF, na.rm = TRUE),
                              pct_high_maf = 100 * mean(MAF >= 0.40, na.rm = TRUE)),
                          by = .(chrom = CHR)]
summary_df <- summary_df %>% left_join(as_tibble(maf_per_chrom), by = "chrom")
write_tsv(summary_df, out_summary, na = "NA")
log_msg(sprintf("  wrote: %s", out_summary))

p4 <- ggplot(frq_auto, aes(x = MAF, fill = group)) +
  geom_histogram(binwidth = 0.01, alpha = 0.65, position = "identity",
                 color = "grey20", linewidth = 0.05,
                 aes(y = after_stat(density))) +
  scale_fill_manual(values = c(chr_1 = "#D55E00",
                                other_autosomes = "#5B8AB7"),
                    labels = c("chr 1", "other autosomes")) +
  labs(
    title    = "Check 4: MAF distribution, chr 1 vs other autosomes (PLINK universe)",
    subtitle = sprintf("chr 1 mean MAF: %.3f (n=%s);   other autosomes mean MAF: %.3f (n=%s)",
                       maf_summary$mean_maf[maf_summary$group == "chr_1"],
                       format(maf_summary$n[maf_summary$group == "chr_1"], big.mark = ","),
                       maf_summary$mean_maf[maf_summary$group == "other_autosomes"],
                       format(maf_summary$n[maf_summary$group == "other_autosomes"], big.mark = ",")),
    x = "Minor allele frequency (PLINK --freq)",
    y = "Density",
    fill = "Group"
  ) +
  theme_bw(base_size = 9) +
  theme(plot.title = element_text(face = "bold", size = 10),
        plot.subtitle = element_text(size = 8.5),
        legend.position = "bottom")
ggsave(file.path(fig_dir, "check4_maf_chr1_vs_other.png"),
       p4, width = 200, height = 110, units = "mm", dpi = 200)
log_msg("  wrote: check4_maf_chr1_vs_other.png")

# --- Combined summary panel -------------------------------------------------

log_msg("\n[5] Writing combined 4-panel summary figure")

combined <- (p1a | p1b) /
            (p3 + theme(legend.position = "none") |
             p4 + theme(legend.position = "none")) +
  plot_annotation(
    title = "chr-1 follow-up: 4-check diagnostic panel",
    subtitle = "Top: SNP density (pre / post FST filter). Bottom: FST among outliers (chr_1 vs others); MAF distribution.",
    caption = "Panel for the spatial check (check 2) is in check2_chr1_spatial_distribution.png.",
    theme = theme(plot.title    = element_text(face = "bold", size = 11),
                  plot.subtitle = element_text(size = 9),
                  plot.caption  = element_text(size = 7, color = "grey40", hjust = 0))
  )
ggsave(file.path(fig_dir, "summary_panel.png"),
       combined, width = 280, height = 200, units = "mm", dpi = 200)
log_msg("  wrote: summary_panel.png")

writeLines(log_lines, out_log)
log_msg(sprintf("\nRun log: %s", out_log))
