# title: pcadapt_selection_scan.R
# project: BIOL624 Final Project
# author: Reina Hastings (reinahastings13@gmail.com)
# date created: 2026-01-12
# last modified: 2026-04-29 (K-sensitivity audit: K = 2 retained as the
#                             canonical pcadapt run, but the rationale
#                             section below now reflects a multi-criterion
#                             diagnostic battery rather than a single auto-
#                             detected scree value. Strict Cattell favors
#                             K = 1; Kaiser and Horn favor K = 5; K = 2 is
#                             an analyst-driven choice supported on
#                             biological grounds. Outputs unchanged. See
#                             results/pcadapt/diagnostics/diagnostic_report.md.)
#                2026-04-13 (initial scan + scree-based K = 2 selection)
#
# purpose:
#   Full pcadapt selection scan on C. septempunctata population genomic data.
#   Identifies SNPs under selection using population-structure-free PCA-based
#   outlier detection. Classifies outliers by PC loading into biological
#   pattern categories (INVASION_SPECIFIC, POST_INVASION, BOTH).
#
#   Workflow:
#     Step 1: PLINK file regeneration (done externally via plink --remove)
#     Step 2: Scree plot for K selection (done in pcadapt_step2_3_checkin.R)
#     Step 3: PCA missingness inspection (done in pcadapt_step2_3_checkin.R)
#     Step 4: Run pcadapt with K=2, check lambda (genomic inflation)
#     Step 5: FDR correction (Storey's q-value), extract outliers
#     Step 6: Classify outliers by PC loading (|z| > 2 per component)
#     Step 7: Generate diagnostic plots (Manhattan, Q-Q)
#     Step 8: Write output files and summary report
#
# inputs:
#   - data/plink/ladybug_snps_pcadapt.bed (81 individuals, 7 high-miss excluded)
#   - data/plink/ladybug_snps_pcadapt.bim (SNP info: chrom, pos)
#   - data/plink/ladybug_snps_pcadapt.imiss (per-sample missingness)
#   - metadata/pop_CHI.txt, pop_EEU.txt, pop_WEU.txt, pop_USA.txt
#
# outputs:
#   results/pcadapt/
#     pcadapt_outliers_q05.tsv -- all outliers at q < 0.05
#     pcadapt_outliers_q01.tsv -- stringent subset at q < 0.01
#     pcadapt_summary.txt      -- K, lambda, outlier counts, sample info
#   results/pcadapt/plots/
#     screeplot.png             (generated by step2_3 script)
#     pca_scores_by_pop.png     (generated by step2_3 script)
#     pca_scores_by_missingness.png (generated by step2_3 script)
#     manhattan.png             -- -log10(p) across chromosomes
#     qqplot.png                -- observed vs expected p-values
#
# usage example:
#   conda activate pop_gen
#   Rscript scripts/pcadapt_selection_scan.R
#
# copy/paste: Rscript scripts/pcadapt_selection_scan.R

################################################################################
# LIBRARIES
################################################################################

suppressPackageStartupMessages({
  library(pcadapt)
  library(qvalue)
  library(ggplot2)
  library(dplyr)
})

################################################################################
# CONFIGURATION
################################################################################

PLINK_PREFIX <- 'data/plink/ladybug_snps_pcadapt'
IMISS_FILE   <- 'data/plink/ladybug_snps_pcadapt.imiss'
POP_DIR      <- 'metadata'
OUTPUT_DIR   <- 'results/pcadapt'
PLOT_DIR     <- 'results/pcadapt/plots'

# Analysis parameters
# K: analyst-driven choice supported by the 2026-04-29 K-sensitivity audit
# (results/pcadapt/diagnostics/diagnostic_report.md). The strict Cattell
# scree test favors K = 1; Kaiser-Guttman and Horn's parallel analysis
# favor K = 5. K = 2 is justified for this dataset because (a) PC2
# separates WEU from USA on the score plot (mean PC2 = +0.091 in WEU vs
# -0.063 in USA, with EEU intermediate), (b) |PC2 loading| correlates
# with per-SNP among-invasive max FST (Spearman rho = 0.22, top decile
# 3.4x the bottom-decile mean FST), and (c) the K=2-only outliers
# (relative to K=1) are enriched for high among-invasive FST (52% above
# the 0.190 panel-specific top-1% threshold vs 38% for K=1-only outliers),
# so K=2 contributes signal rather than noise to the cross-method
# concordance call. K=3 was rejected because PC3 shows no population
# separation on the score plot.
K <- 2                     # See K rationale block above and diagnostic_report.md
Q_THRESHOLD_PRIMARY <- 0.05  # Storey's q-value, primary
Q_THRESHOLD_STRINGENT <- 0.01  # Storey's q-value, stringent
Z_THRESHOLD <- 2           # Component-wise significance for PC loading
LAMBDA_MAX <- 1.5          # Genomic inflation factor threshold

# Samples excluded from PLINK file (for reporting)
EXCLUDED_SAMPLES <- c('SUS5', 'MUS113', 'CZE10', 'MUS114', 'DEU8', 'CHN11', 'SUS66')

# Population color palette
POP_COLORS <- c('CHI' = '#E41A1C', 'EEU' = '#377EB8', 'WEU' = '#4DAF4A', 'USA' = '#984EA3')

# Chromosome order for Manhattan plot
CHROM_ORDER <- c('NC_058189.1', 'NC_058190.1', 'NC_058191.1', 'NC_058192.1',
                 'NC_058193.1', 'NC_058194.1', 'NC_058195.1', 'NC_058196.1',
                 'NC_058197.1', 'NC_058198.1')

dir.create(PLOT_DIR, recursive = TRUE, showWarnings = FALSE)

################################################################################
# SETUP: LOAD DATA AND POPULATION ASSIGNMENTS
################################################################################

cat('\n')
cat('========================================================================\n')
cat('PCADAPT SELECTION SCAN (Steps 4-8)\n')
cat('========================================================================\n')
cat('Start time:', format(Sys.time(), '%Y-%m-%d %H:%M:%S'), '\n')
cat('K =', K, '| q thresholds:', Q_THRESHOLD_PRIMARY, '/', Q_THRESHOLD_STRINGENT, '\n')
cat('========================================================================\n\n')

# --- Load PLINK data ---

cat('--- Loading Data ---\n\n')

bed_file <- paste0(PLINK_PREFIX, '.bed')
bim_file <- paste0(PLINK_PREFIX, '.bim')
fam_file <- paste0(PLINK_PREFIX, '.fam')

# Read .bim for SNP info (chrom, pos)
bim <- read.table(bim_file, stringsAsFactors = FALSE,
                  col.names = c('chrom', 'snp_id', 'cm', 'pos', 'a1', 'a2'))
cat('SNPs in BIM:', nrow(bim), '\n')

# Read .fam for sample info
fam <- read.table(fam_file, stringsAsFactors = FALSE)
sample_ids <- fam$V2
cat('Samples in FAM:', length(sample_ids), '\n')

# --- Assign populations ---

pop_files <- c('CHI' = 'pop_CHI.txt', 'EEU' = 'pop_EEU.txt',
               'WEU' = 'pop_WEU.txt', 'USA' = 'pop_USA.txt')

pop_labels <- rep(NA_character_, length(sample_ids))
for (pop_name in names(pop_files)) {
  pop_samples <- readLines(file.path(POP_DIR, pop_files[pop_name]))
  pop_samples <- trimws(pop_samples[nchar(trimws(pop_samples)) > 0])
  pop_samples <- setdiff(pop_samples, EXCLUDED_SAMPLES)
  pop_labels[sample_ids %in% pop_samples] <- pop_name
}

pop_counts <- table(factor(pop_labels, levels = c('CHI', 'EEU', 'WEU', 'USA')))
cat('Population sizes:', paste(names(pop_counts), pop_counts, sep = '=', collapse = ', '), '\n')

# --- Load missingness ---

imiss <- read.table(IMISS_FILE, header = TRUE, stringsAsFactors = FALSE)
miss_rate <- imiss$F_MISS[match(sample_ids, imiss$IID)]

################################################################################
# STEP 4: RUN PCADAPT WITH K=2, CHECK LAMBDA
################################################################################

cat('\n--- Step 4: Running pcadapt with K =', K, '---\n\n')

geno <- read.pcadapt(bed_file, type = 'bed')
x <- pcadapt(geno, K = K)

# Genomic inflation factor
lambda <- median(x$chi2.stat, na.rm = TRUE) / qchisq(0.5, df = K)
cat('Genomic inflation factor (lambda):', round(lambda, 4), '\n')

if (lambda > LAMBDA_MAX) {
  cat('\n*** WARNING: Lambda =', round(lambda, 4), '> threshold', LAMBDA_MAX, '***\n')
  cat('*** LD pruning recommended. Running PLINK --indep-pairwise 50 10 0.1 ***\n')
  cat('*** This would require regenerating PLINK files and re-running. ***\n')
  cat('*** For now, proceeding with unpruned results but flagging in report. ***\n\n')
  lambda_flag <- TRUE
} else {
  cat('Lambda is within acceptable range (<=', LAMBDA_MAX, '). No LD pruning needed.\n')
  lambda_flag <- FALSE
}

# Variance explained
var_explained <- x$singular.values^2 / sum(x$singular.values^2)
cat('Variance explained: PC1 =', round(var_explained[1] * 100, 2),
    '%, PC2 =', round(var_explained[2] * 100, 2), '%\n')

################################################################################
# STEP 5: STOREY'S Q-VALUE FDR CORRECTION
################################################################################

cat('\n--- Step 5: FDR Correction (Storey q-value) ---\n\n')

# Get p-values (some may be NA for monomorphic/invariant SNPs)
pvalues <- x$pvalues
n_valid_pvalues <- sum(!is.na(pvalues))
n_na_pvalues <- sum(is.na(pvalues))
cat('Valid p-values:', n_valid_pvalues, '\n')
cat('NA p-values (invariant SNPs):', n_na_pvalues, '\n')

# Storey's q-value
qval_obj <- qvalue(pvalues[!is.na(pvalues)])
cat('Estimated pi0 (proportion true nulls):', round(qval_obj$pi0, 4), '\n')

# Map q-values back to full SNP vector
qvalues <- rep(NA_real_, length(pvalues))
qvalues[!is.na(pvalues)] <- qval_obj$qvalues

# Count outliers
n_outliers_q05 <- sum(qvalues < Q_THRESHOLD_PRIMARY, na.rm = TRUE)
n_outliers_q01 <- sum(qvalues < Q_THRESHOLD_STRINGENT, na.rm = TRUE)
cat('\nOutliers at q < 0.05:', n_outliers_q05, '\n')
cat('Outliers at q < 0.01:', n_outliers_q01, '\n')

# Sanity check
if (n_outliers_q05 > 10000) {
  cat('*** WARNING: >10,000 outliers at q<0.05. Check lambda, consider LD pruning. ***\n')
} else if (n_outliers_q05 < 100) {
  cat('*** WARNING: <100 outliers at q<0.05. Check K choice, verify PCA structure. ***\n')
}

################################################################################
# STEP 6: CLASSIFY OUTLIERS BY PC LOADING (|z| > 2)
################################################################################

cat('\n--- Step 6: PC Loading Classification ---\n\n')

# Build results data frame
results <- data.frame(
  snp_index = seq_len(nrow(bim)),
  chrom     = bim$chrom,
  pos       = bim$pos,
  snp_id    = paste0(bim$chrom, ':', bim$pos),
  z_PC1     = x$zscores[, 1],
  z_PC2     = x$zscores[, 2],
  mahalanobis_dist = x$chi2.stat,
  pvalue    = pvalues,
  qvalue    = qvalues,
  stringsAsFactors = FALSE
)

# Classify each outlier by component-wise significance
# Per spec: |z| > 2 threshold per component
results$pc_category <- NA_character_

outlier_mask_q05 <- !is.na(results$qvalue) & results$qvalue < Q_THRESHOLD_PRIMARY

for (i in which(outlier_mask_q05)) {
  z1 <- abs(results$z_PC1[i])
  z2 <- abs(results$z_PC2[i])

  high_pc1 <- !is.na(z1) && z1 > Z_THRESHOLD
  high_pc2 <- !is.na(z2) && z2 > Z_THRESHOLD

  if (high_pc1 && high_pc2) {
    results$pc_category[i] <- 'BOTH'
  } else if (high_pc1) {
    results$pc_category[i] <- 'INVASION_SPECIFIC'
  } else if (high_pc2) {
    results$pc_category[i] <- 'POST_INVASION'
  } else {
    # Neither individually > 2 but overall significant: combined effect
    results$pc_category[i] <- 'BOTH'
  }
}

# Report category counts
cat('PC loading classification (|z| > 2 threshold):\n')
cat('  NOTE: PC1 = CHI vs invasive, PC2 = among invasive\n')
cat('  (Verified from PCA score plot: CHI separated on PC1)\n\n')
cat_counts <- table(results$pc_category[outlier_mask_q05])
for (cat_name in c('INVASION_SPECIFIC', 'POST_INVASION', 'BOTH')) {
  n <- ifelse(cat_name %in% names(cat_counts), cat_counts[cat_name], 0)
  cat(' ', cat_name, ':', n, '\n')
}
cat('  Total:', sum(cat_counts), '\n')

# Also classify q < 0.01 subset
outlier_mask_q01 <- !is.na(results$qvalue) & results$qvalue < Q_THRESHOLD_STRINGENT
cat('\nStringent subset (q < 0.01):\n')
cat_counts_q01 <- table(results$pc_category[outlier_mask_q01])
for (cat_name in c('INVASION_SPECIFIC', 'POST_INVASION', 'BOTH')) {
  n <- ifelse(cat_name %in% names(cat_counts_q01), cat_counts_q01[cat_name], 0)
  cat(' ', cat_name, ':', n, '\n')
}
cat('  Total:', sum(cat_counts_q01), '\n')

################################################################################
# STEP 7: DIAGNOSTIC PLOTS
################################################################################

cat('\n--- Step 7: Generating Diagnostic Plots ---\n\n')

# --- Manhattan Plot ---

cat('Creating Manhattan plot...\n')

# Add chromosome number for ordering
results$chrom_num <- match(results$chrom, CHROM_ORDER)

# Calculate cumulative positions for Manhattan-style x-axis
chrom_sizes <- results %>%
  group_by(chrom_num) %>%
  summarize(max_pos = max(pos), .groups = 'drop') %>%
  arrange(chrom_num)

chrom_sizes$cumul_offset <- cumsum(c(0, head(chrom_sizes$max_pos, -1)))

results <- results %>%
  left_join(chrom_sizes %>% select(chrom_num, cumul_offset), by = 'chrom_num') %>%
  mutate(bp_cumul = pos + cumul_offset)

# Chromosome label positions (midpoint)
chrom_labels <- results %>%
  group_by(chrom_num) %>%
  summarize(center = (min(bp_cumul) + max(bp_cumul)) / 2, .groups = 'drop')

# Subsample non-outliers for plotting performance
results$neg_log10_p <- -log10(results$pvalue)

plot_data <- results %>% filter(!is.na(pvalue))
if (nrow(plot_data) > 100000) {
  outlier_rows <- plot_data %>% filter(outlier_mask_q05[!is.na(pvalues)])
  non_outlier_rows <- plot_data %>% filter(!outlier_mask_q05[!is.na(pvalues)])
  set.seed(42)
  sampled_non <- non_outlier_rows %>% slice_sample(n = min(80000, nrow(non_outlier_rows)))
  plot_data <- bind_rows(sampled_non, outlier_rows)
}

# Color outliers by category
plot_data$plot_color <- 'non-outlier'
plot_data$plot_color[!is.na(plot_data$pc_category)] <- plot_data$pc_category[!is.na(plot_data$pc_category)]

color_values <- c(
  'non-outlier' = 'grey70',
  'INVASION_SPECIFIC' = '#E41A1C',
  'POST_INVASION' = '#377EB8',
  'BOTH' = '#984EA3'
)

# Cap Inf values at max finite value for plotting
max_finite_nlp <- max(plot_data$neg_log10_p[is.finite(plot_data$neg_log10_p)], na.rm = TRUE)
n_inf <- sum(is.infinite(plot_data$neg_log10_p))
plot_data$neg_log10_p[is.infinite(plot_data$neg_log10_p)] <- max_finite_nlp

# Apply sqrt transform to y-axis values
plot_data$sqrt_neg_log10_p <- sqrt(plot_data$neg_log10_p)

p_manhattan <- ggplot(plot_data, aes(x = bp_cumul, y = sqrt_neg_log10_p)) +
  # Non-outliers: alternating shading by chromosome
  geom_point(data = filter(plot_data, plot_color == 'non-outlier'),
             aes(color = as.factor(chrom_num %% 2)),
             size = 0.3, alpha = 0.4) +
  scale_color_manual(values = c('0' = 'grey60', '1' = 'grey80'), guide = 'none') +
  # Outliers on top, colored by category
  ggnewscale::new_scale_color() +
  geom_point(data = filter(plot_data, plot_color != 'non-outlier'),
             aes(color = plot_color), size = 1, alpha = 0.7) +
  scale_color_manual(
    values = color_values[c('INVASION_SPECIFIC', 'POST_INVASION', 'BOTH')],
    name = 'Category'
  ) +
  scale_x_continuous(breaks = chrom_labels$center,
                     labels = paste0('Chr', seq_len(nrow(chrom_labels)))) +
  labs(
    title = 'pcadapt Manhattan Plot',
    subtitle = paste0(n_outliers_q05, ' outliers at q < 0.05 | K = ', K,
                      ' | lambda = ', round(lambda, 3),
                      if (n_inf > 0) paste0(' | ', n_inf, ' SNPs with p underflow capped')),
    x = 'Chromosome',
    y = expression(sqrt(-log[10](p)))
  ) +
  theme_minimal(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    legend.position = 'bottom',
    panel.grid.minor = element_blank()
  )

ggsave(file.path(PLOT_DIR, 'manhattan.png'), p_manhattan, width = 14, height = 6, dpi = 300)
cat('Manhattan plot saved.\n')

# --- Q-Q Plot (sqrt-transformed axes) ---

cat('Creating Q-Q plot...\n')

valid_p <- sort(pvalues[!is.na(pvalues)])
n_p <- length(valid_p)
expected_p <- (1:n_p) / (n_p + 1)

qq_df <- data.frame(
  expected = -log10(expected_p),
  observed = -log10(valid_p)
)

# Cap Inf values at max finite observed value
max_finite_obs <- max(qq_df$observed[is.finite(qq_df$observed)])
n_inf_qq <- sum(is.infinite(qq_df$observed))
qq_df$observed[is.infinite(qq_df$observed)] <- max_finite_obs

# Apply sqrt transform
qq_df$sqrt_expected <- sqrt(qq_df$expected)
qq_df$sqrt_observed <- sqrt(qq_df$observed)

# Subsample middle portion for performance (keep tails)
if (nrow(qq_df) > 50000) {
  keep_top <- qq_df %>% filter(observed > quantile(observed, 0.99))
  keep_bottom <- qq_df %>% filter(expected < 1)
  middle <- qq_df %>%
    filter(observed <= quantile(observed, 0.99), expected >= 1) %>%
    slice_sample(n = 20000)
  qq_df_plot <- bind_rows(keep_top, keep_bottom, middle) %>% arrange(expected)
} else {
  qq_df_plot <- qq_df
}

# Reference line: sqrt(x) = sqrt(y) when x = y (identity on original scale)
ref_max <- max(qq_df_plot$sqrt_expected)
ref_line <- data.frame(x = seq(0, ref_max, length.out = 200))
ref_line$y <- ref_line$x

p_qq <- ggplot(qq_df_plot, aes(x = sqrt_expected, y = sqrt_observed)) +
  geom_point(size = 0.5, alpha = 0.5, color = 'steelblue') +
  geom_line(data = ref_line, aes(x = x, y = y),
            color = 'red', linetype = 'dashed', linewidth = 0.8) +
  labs(
    title = 'Q-Q Plot of pcadapt p-values (sqrt-transformed axes)',
    subtitle = paste0('Lambda = ', round(lambda, 3),
                      ' | pi0 = ', round(qval_obj$pi0, 3),
                      if (n_inf_qq > 0) paste0(' | ', n_inf_qq, ' p-value underflows capped')),
    x = expression(sqrt(Expected ~ -log[10](p))),
    y = expression(sqrt(Observed ~ -log[10](p)))
  ) +
  theme_minimal(base_size = 12)

ggsave(file.path(PLOT_DIR, 'qqplot.png'), p_qq, width = 9, height = 7, dpi = 300)
cat('Q-Q plot saved.\n')

# --- Manhattan without ggnewscale fallback ---
# If ggnewscale is not available, generate a simpler Manhattan plot

tryCatch({
  if (!requireNamespace('ggnewscale', quietly = TRUE)) {
    cat('NOTE: ggnewscale not available, generating simplified Manhattan plot...\n')

    # Simple version: all points, outliers highlighted
    plot_data$is_outlier <- plot_data$plot_color != 'non-outlier'

    p_manhattan_simple <- ggplot() +
      geom_point(data = filter(plot_data, !is_outlier),
                 aes(x = bp_cumul, y = neg_log10_p,
                     color = as.factor(chrom_num %% 2)),
                 size = 0.3, alpha = 0.4) +
      geom_point(data = filter(plot_data, is_outlier),
                 aes(x = bp_cumul, y = neg_log10_p),
                 color = 'red', size = 1, alpha = 0.7) +
      scale_color_manual(values = c('0' = 'grey60', '1' = 'grey80'), guide = 'none') +
      scale_x_continuous(breaks = chrom_labels$center,
                         labels = paste0('Chr', seq_len(nrow(chrom_labels)))) +
      labs(
        title = 'pcadapt Manhattan Plot',
        subtitle = paste0(n_outliers_q05, ' outliers at q < 0.05 (red) | K = ', K,
                          ' | lambda = ', round(lambda, 3)),
        x = 'Chromosome',
        y = expression(-log[10](p))
      ) +
      theme_minimal(base_size = 11) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
            panel.grid.minor = element_blank())

    ggsave(file.path(PLOT_DIR, 'manhattan.png'), p_manhattan_simple,
           width = 14, height = 6, dpi = 300)
    cat('Simplified Manhattan plot saved (no ggnewscale).\n')
  }
}, error = function(e) {
  cat('Manhattan plot error:', conditionMessage(e), '\n')
  cat('Attempting simplified version...\n')
})

################################################################################
# STEP 8: WRITE OUTPUT FILES
################################################################################

cat('\n--- Step 8: Writing Output Files ---\n\n')

# --- Outlier tables ---

# q < 0.05 (primary)
outliers_q05 <- results %>%
  filter(!is.na(qvalue), qvalue < Q_THRESHOLD_PRIMARY) %>%
  select(snp_index, chrom, pos, snp_id, z_PC1, z_PC2,
         mahalanobis_dist, pvalue, qvalue, pc_category) %>%
  arrange(qvalue)

write.table(outliers_q05, file.path(OUTPUT_DIR, 'pcadapt_outliers_q05.tsv'),
            sep = '\t', row.names = FALSE, quote = FALSE)
cat('Saved:', nrow(outliers_q05), 'outliers at q < 0.05\n')

# q < 0.01 (stringent)
outliers_q01 <- results %>%
  filter(!is.na(qvalue), qvalue < Q_THRESHOLD_STRINGENT) %>%
  select(snp_index, chrom, pos, snp_id, z_PC1, z_PC2,
         mahalanobis_dist, pvalue, qvalue, pc_category) %>%
  arrange(qvalue)

write.table(outliers_q01, file.path(OUTPUT_DIR, 'pcadapt_outliers_q01.tsv'),
            sep = '\t', row.names = FALSE, quote = FALSE)
cat('Saved:', nrow(outliers_q01), 'outliers at q < 0.01\n')

# --- Summary report ---

cat('\nWriting summary report...\n')

summary_file <- file.path(OUTPUT_DIR, 'pcadapt_summary.txt')
sink(summary_file)

cat('================================================================================\n')
cat('PCADAPT SELECTION SCAN SUMMARY\n')
cat('================================================================================\n')
cat('Generated:', format(Sys.time(), '%Y-%m-%d %H:%M:%S'), '\n')
cat('Script: scripts/pcadapt_selection_scan.R\n\n')

cat('INPUT DATA\n')
cat('----------\n')
cat('PLINK file:', bed_file, '\n')
cat('Total SNPs:', nrow(bim), '\n')
cat('Total samples:', length(sample_ids), '(post-exclusion)\n')
cat('Excluded samples (>50% missing):', paste(EXCLUDED_SAMPLES, collapse = ', '), '\n')
cat('Population sizes:', paste(names(pop_counts), pop_counts, sep = '=', collapse = ', '), '\n')
cat('Genotyping rate: 93.7%\n')
cat('Mean per-sample missingness:', round(mean(miss_rate) * 100, 2), '%\n\n')

cat('PCADAPT PARAMETERS\n')
cat('------------------\n')
cat('K:', K, '(analyst-driven choice; not auto-selected from scree plot)\n')
cat('K rationale (post 2026-04-29 K-sensitivity audit):\n')
cat('  Three independent K criteria computed in pcadapt_step2_3_checkin.R:\n')
cat('    Cattell strict (no min-floor): K = 1\n')
cat('    Kaiser-Guttman (var > 1/N):    K = 5\n')
cat('    Horn parallel analysis (95%):  K = 5\n')
cat('  K=2 is an analytical choice on top of these diagnostics, supported by:\n')
cat('  - PC1 cleanly separates CHI from invasives; PC2 separates WEU (+0.09)\n')
cat('    from USA (-0.06) on the score plot.\n')
cat('  - |PC2 loading| correlates with per-SNP among-invasive max FST\n')
cat('    (Spearman rho = 0.22; top decile 3.4x bottom-decile mean FST).\n')
cat('  - K=2-only outliers (vs K=1) are enriched for high among-invasive FST\n')
cat('    (52% above the panel top-1%% threshold, vs 38%% for K=1-only).\n')
cat('  - PC3 shows no population separation on the score plot, so K=3 is\n')
cat('    over-fit (would absorb signal as structure).\n')
cat('  See results/pcadapt/diagnostics/diagnostic_report.md for the full audit.\n')
cat('Method: Mahalanobis distance (default)\n')
cat('LD pruning: None (unpruned)\n')
cat('FDR method: Storey q-value\n')
cat('Primary threshold: q <', Q_THRESHOLD_PRIMARY, '\n')
cat('Stringent threshold: q <', Q_THRESHOLD_STRINGENT, '\n')
cat('PC loading threshold: |z| >', Z_THRESHOLD, 'per component\n\n')

cat('GENOMIC INFLATION\n')
cat('-----------------\n')
cat('Lambda:', round(lambda, 4), '\n')
if (lambda_flag) {
  cat('STATUS: ELEVATED (> ', LAMBDA_MAX, '). LD pruning may be needed.\n')
} else {
  cat('STATUS: Acceptable (<= ', LAMBDA_MAX, '). No LD pruning needed.\n')
}
cat('\n')

cat('VARIANCE EXPLAINED\n')
cat('------------------\n')
cat('PC1:', round(var_explained[1] * 100, 2), '%\n')
cat('PC2:', round(var_explained[2] * 100, 2), '%\n\n')

cat('ESTIMATED PI0\n')
cat('-------------\n')
cat('pi0 (proportion true nulls):', round(qval_obj$pi0, 4), '\n')
cat('Estimated true positives:', round((1 - qval_obj$pi0) * n_valid_pvalues), '\n\n')

cat('OUTLIER COUNTS\n')
cat('--------------\n')
cat('q < 0.05:', n_outliers_q05, '\n')
cat('q < 0.01:', n_outliers_q01, '\n')
cat('NA p-values (invariant):', n_na_pvalues, '\n\n')

cat('OUTLIER CLASSIFICATION (q < 0.05)\n')
cat('---------------------------------\n')
cat('PC interpretation:\n')
cat('  PC1 = CHI vs invasive (INVASION_SPECIFIC)\n')
cat('  PC2 = among invasive (POST_INVASION)\n')
cat('Classification threshold: |z| >', Z_THRESHOLD, 'per component\n\n')
for (cat_name in c('INVASION_SPECIFIC', 'POST_INVASION', 'BOTH')) {
  n <- ifelse(cat_name %in% names(cat_counts), cat_counts[cat_name], 0)
  pct <- round(100 * n / n_outliers_q05, 1)
  cat(' ', cat_name, ':', n, '(', pct, '%)\n')
}
cat('\n')

cat('OUTLIER CLASSIFICATION (q < 0.01)\n')
cat('---------------------------------\n')
for (cat_name in c('INVASION_SPECIFIC', 'POST_INVASION', 'BOTH')) {
  n <- ifelse(cat_name %in% names(cat_counts_q01), cat_counts_q01[cat_name], 0)
  pct <- round(100 * n / max(n_outliers_q01, 1), 1)
  cat(' ', cat_name, ':', n, '(', pct, '%)\n')
}
cat('\n')

cat('BORDERLINE SAMPLES (kept after PCA inspection)\n')
cat('-----------------------------------------------\n')
cat('WUS7 (USA, 38.75% missing): clusters normally with USA\n')
cat('NLD3 (WEU, 32.16% missing): clusters normally with WEU\n')
cat('DEU12 (WEU, 29.46% missing): clusters normally with WEU\n')
cat('SVK1 (EEU, 20.31% missing): clusters normally with EEU\n')
cat('Decision: All kept (no missingness-driven PCA drift detected)\n\n')

cat('CHROMOSOME DISTRIBUTION OF OUTLIERS (q < 0.05)\n')
cat('-----------------------------------------------\n')
chrom_dist <- outliers_q05 %>%
  group_by(chrom) %>%
  summarize(n = n(), .groups = 'drop') %>%
  arrange(match(chrom, CHROM_ORDER))
for (i in seq_len(nrow(chrom_dist))) {
  cat(sprintf('  Chr%d (%s): %d outliers\n', i, chrom_dist$chrom[i], chrom_dist$n[i]))
}
cat('\n')

cat('OUTPUT FILES\n')
cat('------------\n')
cat('results/pcadapt/pcadapt_outliers_q05.tsv\n')
cat('results/pcadapt/pcadapt_outliers_q01.tsv\n')
cat('results/pcadapt/pcadapt_summary.txt\n')
cat('results/pcadapt/plots/screeplot.png\n')
cat('results/pcadapt/plots/pca_scores_by_pop.png\n')
cat('results/pcadapt/plots/pca_scores_by_missingness.png\n')
cat('results/pcadapt/plots/manhattan.png\n')
cat('results/pcadapt/plots/qqplot.png\n')

cat('\n================================================================================\n')
sink()

cat('Summary report saved to:', summary_file, '\n')

################################################################################
# FINAL CONSOLE REPORT
################################################################################

cat('\n')
cat('========================================================================\n')
cat('PCADAPT SELECTION SCAN COMPLETE\n')
cat('========================================================================\n')
cat('End time:', format(Sys.time(), '%Y-%m-%d %H:%M:%S'), '\n\n')
cat('Key results:\n')
cat('  K:', K, '\n')
cat('  Lambda:', round(lambda, 4), '\n')
cat('  pi0:', round(qval_obj$pi0, 4), '\n')
cat('  Outliers (q<0.05):', n_outliers_q05, '\n')
cat('  Outliers (q<0.01):', n_outliers_q01, '\n')
cat('\n  Category breakdown (q<0.05):\n')
for (cat_name in c('INVASION_SPECIFIC', 'POST_INVASION', 'BOTH')) {
  n <- ifelse(cat_name %in% names(cat_counts), cat_counts[cat_name], 0)
  cat('   ', cat_name, ':', n, '\n')
}
if (lambda_flag) {
  cat('\n  *** Lambda elevated -- consider LD pruning and re-running ***\n')
}
cat('\n========================================================================\n')
