#!/usr/bin/env Rscript

# title: plot_diversity.R
# project: BIOL624 Final Project — Selection Detection in Lady Beetles
# author: Reina Hastings
# contact: reinahastings13@gmail.com
# date created: 2025-11-17
# last modified: 2025-11-20
# purpose:
#   Generate per-chromosome and combined Tajima’s D and nucleotide diversity
#   (pi) plots using output files generated by diversity.sh.
#
# inputs:
#   - results_dir: directory containing:
#         results_dir/tajima/*.Tajima.D
#         results_dir/pi/*.windowed.pi
#   - chromosome arguments:
#         <chr1> [<chr2> ...]   or   'all' to auto-detect chromosomes
#
# outputs:
#   - results_dir/figs/diversity/TajimaD_<chr>.png
#   - results_dir/figs/diversity/pi_<chr>.png
#   - results_dir/figs/diversity/All_TajimaD_faceted_<label>.png
#   - results_dir/figs/diversity/All_pi_faceted_<label>.png
#
# required R libraries:
#   - tidyverse
#
# usage examples:
#   # Whole-population results (all samples)
#   Rscript plot_diversity.R ../results/whole_pop_results all
#
#   # Continent-level results (population files created by create_metadata.py)
#   Rscript plot_diversity.R ../results/CHI_results all
#   Rscript plot_diversity.R ../results/WEU_results all
#   Rscript plot_diversity.R ../results/EEU_results all
#   Rscript plot_diversity.R ../results/USA_results all
#
#   # Specific chromosomes only
#   Rscript plot_diversity.R ../results/USA_results NC_058189.1.filtered NC_058190.1.filtered

suppressPackageStartupMessages({
  library(tidyverse)
})

print_usage <- function() {
  cat(
    "Usage:\n",
    "  Rscript plot_diversity.R <results_dir> <chr1|all> [<chr2> ...]\n\n",
    "Arguments:\n",
    "  results_dir   Directory containing 'tajima' and 'pi' outputs from diversity.sh\n",
    "  chr1|all      One chromosome ID (e.g., NC_058189.1.filtered) or 'all'\n",
    "  chr2 ...      Optional additional chromosome IDs\n\n",
    "Examples:\n",
    "  # Whole population (e.g., diversity.sh -o ../results/whole_pop_results)\n",
    "  Rscript plot_diversity.R ../results/whole_pop_results all\n\n",
    "  # CHI-only stats (e.g., diversity.sh -o ../results/CHI_results -p pop_CHI.txt)\n",
    "  Rscript plot_diversity.R ../results/CHI_results all\n\n",
    "  # Single chromosome\n",
    "  Rscript plot_diversity.R ../results/USA_results NC_058189.1.filtered\n",
    sep = ""
  )
}

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 2) {
  print_usage()
  quit(status = 1)
}

results_dir <- args[1]
chrom_args  <- args[-1]

# label derived from results_dir (used in combined-figure filenames)
results_label <- basename(normalizePath(results_dir))

# clean labels:
#   - strip '_results' suffix if present: 'CHI_results' -> 'CHI'
#   - strip leading 'results_' or 'results-' if present: 'results_Europe' -> 'Europe'
results_label <- sub("_results$",   "", results_label)
results_label <- sub("^results[_-]?", "", results_label)

# directories & setup
taj_dir <- file.path(results_dir, "tajima")
pi_dir  <- file.path(results_dir, "pi")

if (!dir.exists(taj_dir)) {
  stop("Tajima directory not found: ", taj_dir)
}
if (!dir.exists(pi_dir)) {
  stop("Pi directory not found: ", pi_dir)
}

out_dir <- file.path(results_dir, "figs", "diversity")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

message("Results directory: ", results_dir)
message("Derived label: ", results_label)
message("Output directory for plots: ", out_dir)

# chromosomes to plot
if (length(chrom_args) == 1 && chrom_args[1] == "all") {
  taj_files <- list.files(taj_dir, pattern = "\\.Tajima\\.D$", full.names = FALSE)
  if (length(taj_files) == 0) {
    stop("No TajimaD files found in ", taj_dir)
  }
  chroms <- sub("\\.Tajima\\.D$", "", taj_files)
  message("Detected chromosomes from TajimaD files: ",
          paste(chroms, collapse = ", "))
} else {
  chroms <- chrom_args
  message("Using chromosomes specified on command line: ",
          paste(chroms, collapse = ", "))
}

# helper to safely read a file
read_div_file <- function(path, chr, kind) {
  if (!file.exists(path)) {
    warning("Missing ", kind, " file for ", chr, ": ", path)
    return(NULL)
  }
  read.table(path, header = TRUE)
}

# to build combined faceted plots, store all per-window data
all_taj_list <- list()
all_pi_list  <- list()

# per-chromosome plotting
for (chr in chroms) {
  message("Processing ", chr, " ...")

  taj_path <- file.path(taj_dir, paste0(chr, ".Tajima.D"))
  pi_path  <- file.path(pi_dir,  paste0(chr, ".windowed.pi"))

  taj <- read_div_file(taj_path, chr, "TajimaD")
  pi  <- read_div_file(pi_path,  chr, "pi")

  if (is.null(taj) || is.null(pi)) {
    message("  Skipping ", chr, " because one or both files are missing.")
    next
  }

  # drop windows with 0 SNPs/variants if these columns exist
  if ("N_SNPS" %in% names(taj)) {
    taj <- taj %>% filter(N_SNPS > 0)
  }
  if ("N_VARIANTS" %in% names(pi)) {
    pi <- pi %>% filter(N_VARIANTS > 0)
  }

  # standardize pi column to PI_STD
  if ("PI" %in% names(pi)) {
    col_pi <- "PI"
  } else {
    pi_candidates <- names(pi)[grepl("pi", names(pi), ignore.case = TRUE)]
    if (length(pi_candidates) == 0) {
      stop("No PI-like column found in ", pi_path)
    }
    col_pi <- pi_candidates[1]
    warning("Using column '", col_pi, "' as pi in ", pi_path)
  }
  pi$PI_STD <- pi[[col_pi]]

  # add chromosome ID for faceting later
  taj$CHR_ID <- chr
  pi$CHR_ID  <- chr

  # per-chromosome medians
  taj_median <- median(taj$TajimaD, na.rm = TRUE)
  pi_median  <- median(pi$PI_STD,   na.rm = TRUE)

  message(sprintf("  Tajima's D median for %s: %.3f", chr, taj_median))
  message(sprintf("  pi median for %s: %.5f",       chr, pi_median))

  # Tajima's D plot
  p_taj <- ggplot(taj, aes(x = BIN_START, y = TajimaD)) +
    geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.3, alpha = 0.7) +
    geom_hline(yintercept = taj_median, color = "red", linewidth = 0.5, alpha = 0.7) +
    geom_point(alpha = 0.5, size = 0.7) +
    labs(
      title    = paste("Tajima's D -", chr),
      subtitle = sprintf("Median Tajima's D = %.3f", taj_median),
      x        = "Position (bp)",
      y        = "Tajima's D"
    ) +
    theme_bw()

  taj_outfile <- file.path(out_dir, paste0("TajimaD_", chr, ".png"))
  ggsave(taj_outfile, p_taj, width = 7, height = 4, dpi = 300)
  message("  Saved: ", taj_outfile)

  # pi plot (using PI_STD)
  p_pi <- ggplot(pi, aes(x = BIN_START, y = PI_STD)) +
    geom_hline(yintercept = pi_median, color = "red", linewidth = 0.5, alpha = 0.7) +
    geom_point(alpha = 0.5, size = 0.7) +
    labs(
      title    = paste("Nucleotide diversity (pi) -", chr),
      subtitle = sprintf("Median pi = %.5f", pi_median),
      x        = "Position (bp)",
      y        = "pi"
    ) +
    theme_bw()

  pi_outfile <- file.path(out_dir, paste0("pi_", chr, ".png"))
  ggsave(pi_outfile, p_pi, width = 7, height = 4, dpi = 300)
  message("  Saved: ", pi_outfile)

  # store for combined plots
  all_taj_list[[chr]] <- taj
  all_pi_list[[chr]]  <- pi
}

# combined faceted plots ---------------------------------------------

if (length(all_taj_list) > 0) {
  all_taj <- dplyr::bind_rows(all_taj_list)

  taj_meds <- all_taj %>%
    group_by(CHR_ID) %>%
    summarise(taj_median = median(TajimaD, na.rm = TRUE), .groups = "drop")

  p_taj_all <- ggplot(all_taj, aes(x = BIN_START, y = TajimaD)) +
    geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.3, alpha = 0.7) +
    geom_hline(
      data  = taj_meds,
      aes(yintercept = taj_median),
      color = "red", linewidth = 0.4, alpha = 0.7
    ) +
    geom_point(alpha = 0.4, size = 0.5) +
    facet_wrap(~ CHR_ID, scales = "free_x") +
    labs(
      title    = paste0("Tajima's D across chromosomes (", results_label, ")"),
      subtitle = "Red line = chromosome-wide median; dashed line = 0",
      x        = "Position (bp)",
      y        = "Tajima's D"
    ) +
    theme_bw() +
    theme(
      strip.text = element_text(size = 8),
      axis.text.x = element_text(size = 6),
      axis.text.y = element_text(size = 6)
    )

  taj_all_out <- file.path(out_dir, paste0("All_TajimaD_faceted_", results_label, ".png"))
  ggsave(taj_all_out, p_taj_all, width = 10, height = 8, dpi = 300)
  message("Saved combined Tajima's D plot: ", taj_all_out)
} else {
  message("No TajimaD data collected; skipping combined Tajima's D plot.")
}

if (length(all_pi_list) > 0) {
  all_pi <- dplyr::bind_rows(all_pi_list)

  pi_meds <- all_pi %>%
    group_by(CHR_ID) %>%
    summarise(pi_median = median(PI_STD, na.rm = TRUE), .groups = "drop")

  p_pi_all <- ggplot(all_pi, aes(x = BIN_START, y = PI_STD)) +
    geom_hline(
      data  = pi_meds,
      aes(yintercept = pi_median),
      color = "red", linewidth = 0.4, alpha = 0.7
    ) +
    geom_point(alpha = 0.4, size = 0.5) +
    facet_wrap(~ CHR_ID, scales = "free_x") +
    labs(
      title    = paste0("Nucleotide diversity (pi) across chromosomes (", results_label, ")"),
      subtitle = "Red line = chromosome-wide median",
      x        = "Position (bp)",
      y        = "pi"
    ) +
    theme_bw() +
    theme(
      strip.text = element_text(size = 8),
      axis.text.x = element_text(size = 6),
      axis.text.y = element_text(size = 6)
    )

  pi_all_out  <- file.path(out_dir, paste0("All_pi_faceted_", results_label, ".png"))
  ggsave(pi_all_out, p_pi_all, width = 10, height = 8, dpi = 300)
  message("Saved combined pi plot: ", pi_all_out)
} else {
  message("No pi data collected; skipping combined pi plot.")
}

message("Done. Plots written to: ", out_dir)